{{Html::style("/assets/vendors/general/perfect-scrollbar/css/perfect-scrollbar.css")}}
{{Html::style("/assets/vendors/general/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css")}}
{{Html::style("/assets/vendors/general/bootstrap-datetime-picker/css/bootstrap-datetimepicker.css")}}
{{Html::style("/assets/vendors/general/bootstrap-timepicker/css/bootstrap-timepicker.css")}}
{{Html::style("/assets/vendors/general/bootstrap-daterangepicker/daterangepicker.css")}}
{{Html::style("/assets/vendors/general/select2/dist/css/select2.css")}}
{{Html::style("/assets/vendors/general/toastr/build/toastr.css")}}
{{Html::style("/assets/vendors/general/sweetalert2/dist/sweetalert2.css")}}
{{Html::style("/assets/vendors/custom/vendors/flaticon/flaticon.css")}}
{{Html::style("/assets/vendors/custom/vendors/flaticon2/flaticon.css")}}
{{Html::style("/assets/vendors/general/@fortawesome/fontawesome-free/css/all.min.css")}}
{{Html::style("/assets/css/demo10/style.bundle.css")}}
{{Html::style('/assets/vendors/general/bootstrap-select/dist/css/bootstrap-select.css')}}
{{Html::style('/assets/css/demo10/style.bundle.css')}}
{{Html::style('/assets/vendors/general/bootstrap-select/dist/css/bootstrap-select.css')}}
{{Html::style('/assets/vendors/general/sweetalert2/dist/sweetalert2.css')}}
{{Html::style('/assets/vendors/custom/vendors/line-awesome/css/line-awesome.css')}}
{{Html::style('/assets/vendors/custom/vendors/flaticon/flaticon.css')}}
{{Html::style('/assets/vendors/custom/vendors/flaticon2/flaticon.css')}}
